### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by sousuodaren** [wadhwasahil/Relation_Extraction#1]
What's dataset did you use in you code?

**Comment by wadhwasahil** [comment]
I had my own data set. It consisted of multiple texts having multiple entities.

**Comment by venkatraman-arumugam** [comment]
Can you please share a sample line of your dataset, so I can create my dataset in the same format. Thanks.

**Comment by wadhwasahil** [comment]
Due to confidentiality issues, I can't provide you the data. However you can infer from file **data_helpers.py** where the data is read from the csv.

**Comment by venkatraman-arumugam** [comment]
Okay, I got some idea from that file, but what do the columns 'WM1' and 'WM2' represent?

**Comment by wadhwasahil** [comment]
WM1 = entity1 and WM2 = entity2. Here entities in my case were drugs and sideeffects. WM1 and WM2 are basically pairs of drug-sideEffect or vice versa.

**Comment by venkatraman-arumugam** [comment]
Okay thanks a lot
