### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by DanielAbdelNour** [wadhwasahil/Relation_Extraction#2]
Hi there - do you have an example of what the training data looks like? I'd love to try this code out :)

**Comment by wadhwasahil** [comment]
I guess the data should look like this.

```
'System-Id', 'Message', 'drug-offset-start', 'drug-offset-end', 'sideEffect-offset-start', 'sideEffect-offset-end', 'WM1', 'WM2', 'relType'
1, "I have been using taxol for more than 2 years now. But the problem is that it has caused me sever headache.", 19, 24, 99, 108, "taxol", "headache", "causes"
```

**Comment by spathak22** [comment]
Hey Sahil,

I am very interested in trying your code too. Is it possible you could share this dataset?

**Comment by wadhwasahil** [comment]
Unfortunately, the data I uses is under copyright issues and hence I can't share it. But if interested, you could crawl some of the data from online heath forums like [breastcancer.org](breastcancer.org)

**Comment by spathak22** [comment]
Great. Thank you!
